# Site settings
title: "Sam Thompson"
email: 
description: ""
baseurl: ""
url: "http://samthompson.me"
title_description: "I am a software engineer on the core experience team at Pinterest.

I love thinking about mobile app architecture and design and I'm a huge fan of Kotlin and applying functional programming principles to build better mobile apps. I'm also excited about emerging mobile technologies like dartlang/flutter and react native. 

In my spare time I train for XC mountain bike races and explore SF."
title_image: "https://avatars3.githubusercontent.com/u/4391203?v=3&s=460"
google_analytics: "UA-70351113-1"
disqus_account: samthompsonblog
github_repository: https://github.com/st028/st028.github.io
addthis_id: ra-564eb28450457366
post_limit: 5

# Social usernames/URLs
twitter_username: justsamthompson 
github_username:  SamThompson
linkedin_link: https://www.linkedin.com/in/sam-thompson-35617699 
google_plus_link: https://plus.google.com/104557114210568575893
stackoverflow_link: 

# Footer
footer_left: ""
footer_right: "&copy 2017 Sam Thompson"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
